version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: web-speed-hackathon-mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
      MARIADB_DATABASE: "web_speed_hackathon"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
