/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTermsRouteImport } from './routes/_layout/terms'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutCrokRouteImport } from './routes/_layout/crok'
import { Route as LayoutDmIndexRouteImport } from './routes/_layout/dm.index'
import { Route as LayoutUsersUsernameRouteImport } from './routes/_layout/users.$username'
import { Route as LayoutPostsPostIdRouteImport } from './routes/_layout/posts.$postId'
import { Route as LayoutDmConversationIdRouteImport } from './routes/_layout/dm.$conversationId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTermsRoute = LayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrokRoute = LayoutCrokRouteImport.update({
  id: '/crok',
  path: '/crok',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDmIndexRoute = LayoutDmIndexRouteImport.update({
  id: '/dm/',
  path: '/dm/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersUsernameRoute = LayoutUsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostsPostIdRoute = LayoutPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDmConversationIdRoute = LayoutDmConversationIdRouteImport.update({
  id: '/dm/$conversationId',
  path: '/dm/$conversationId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/crok': typeof LayoutCrokRoute
  '/search': typeof LayoutSearchRoute
  '/terms': typeof LayoutTermsRoute
  '/dm/$conversationId': typeof LayoutDmConversationIdRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/users/$username': typeof LayoutUsersUsernameRoute
  '/dm/': typeof LayoutDmIndexRoute
}
export interface FileRoutesByTo {
  '/crok': typeof LayoutCrokRoute
  '/search': typeof LayoutSearchRoute
  '/terms': typeof LayoutTermsRoute
  '/': typeof LayoutIndexRoute
  '/dm/$conversationId': typeof LayoutDmConversationIdRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/users/$username': typeof LayoutUsersUsernameRoute
  '/dm': typeof LayoutDmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/crok': typeof LayoutCrokRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/terms': typeof LayoutTermsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/dm/$conversationId': typeof LayoutDmConversationIdRoute
  '/_layout/posts/$postId': typeof LayoutPostsPostIdRoute
  '/_layout/users/$username': typeof LayoutUsersUsernameRoute
  '/_layout/dm/': typeof LayoutDmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crok'
    | '/search'
    | '/terms'
    | '/dm/$conversationId'
    | '/posts/$postId'
    | '/users/$username'
    | '/dm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/crok'
    | '/search'
    | '/terms'
    | '/'
    | '/dm/$conversationId'
    | '/posts/$postId'
    | '/users/$username'
    | '/dm'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/crok'
    | '/_layout/search'
    | '/_layout/terms'
    | '/_layout/'
    | '/_layout/dm/$conversationId'
    | '/_layout/posts/$postId'
    | '/_layout/users/$username'
    | '/_layout/dm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/terms': {
      id: '/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LayoutTermsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crok': {
      id: '/_layout/crok'
      path: '/crok'
      fullPath: '/crok'
      preLoaderRoute: typeof LayoutCrokRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dm/': {
      id: '/_layout/dm/'
      path: '/dm'
      fullPath: '/dm/'
      preLoaderRoute: typeof LayoutDmIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/$username': {
      id: '/_layout/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof LayoutUsersUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/posts/$postId': {
      id: '/_layout/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutPostsPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dm/$conversationId': {
      id: '/_layout/dm/$conversationId'
      path: '/dm/$conversationId'
      fullPath: '/dm/$conversationId'
      preLoaderRoute: typeof LayoutDmConversationIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCrokRoute: typeof LayoutCrokRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutTermsRoute: typeof LayoutTermsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDmConversationIdRoute: typeof LayoutDmConversationIdRoute
  LayoutPostsPostIdRoute: typeof LayoutPostsPostIdRoute
  LayoutUsersUsernameRoute: typeof LayoutUsersUsernameRoute
  LayoutDmIndexRoute: typeof LayoutDmIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCrokRoute: LayoutCrokRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutTermsRoute: LayoutTermsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDmConversationIdRoute: LayoutDmConversationIdRoute,
  LayoutPostsPostIdRoute: LayoutPostsPostIdRoute,
  LayoutUsersUsernameRoute: LayoutUsersUsernameRoute,
  LayoutDmIndexRoute: LayoutDmIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
