name: Deploy Review App
on:
    pull_request_target:
        types: [opened, reopened, synchronize, closed]

env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    FLY_REGION: nrt
    FLY_ORG: wsh-2026

jobs:
    review_app:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        outputs:
            url: ${{ steps.deploy-open.outputs.url }}
        concurrency:
            group: pr-${{ github.event.number }}
            cancel-in-progress: true

        environment:
            name: deployment
            url: ${{ steps.deploy-open.outputs.url }}

        steps:
            - name: Get code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Generate valid app name
              id: generate-app-name
              run: |
                  APP_NAME=$(grep -oP 'app = "\K[^"]+' fly.toml)
                  APP_NAME="pr-${{ github.event.number }}-${APP_NAME}"
                  echo "app_name=${APP_NAME}" >> $GITHUB_OUTPUT
                  echo "Generated app name: ${APP_NAME}"

            - name: Setup Docker Buildx
              if: github.event.action != 'closed'
              uses: docker/setup-buildx-action@v3

            - name: Login to GHCR
              if: github.event.action != 'closed'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Define image tag
              if: github.event.action != 'closed'
              id: image
              run: |
                  IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/web-speed-hackathon-2026-pr:${{ github.event.pull_request.head.sha }}"
                  echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
                  echo "Image tag: ${IMAGE_TAG}"

            - name: Build and push image
              if: github.event.action != 'closed'
              id: build-image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.image.outputs.tag }}
                  cache-from: type=gha,scope=review-app
                  cache-to: type=gha,mode=max,scope=review-app
                  provenance: false
                  sbom: false

            - name: Deploy PR app to Fly.io
              if: github.event.action != 'closed'
              id: deploy-open
              uses: superfly/fly-pr-review-apps@5d9f067254bebd0aaa77d908d6337b63f4d4f019
              with:
                  name: ${{ steps.generate-app-name.outputs.app_name }}
                  image: ${{ steps.image.outputs.tag }}

            - name: Delete PR app on close
              if: github.event.action == 'closed'
              id: deploy-close
              uses: superfly/fly-pr-review-apps@5d9f067254bebd0aaa77d908d6337b63f4d4f019
              with:
                  name: ${{ steps.generate-app-name.outputs.app_name }}
